### PR TITLE
Update wagtail_modeltranslation to v0.9.0

### PR DESCRIPTION
**Pull request by dalepotter**
~# Ensure #115 is merged before this~ <- Now done

Added as a github download given a known bug with downloading this version using pip: https://github.com/infoportugal/wagtail-modeltranslation/issues/203#issuecomment-385328642

v0.9.0 is needed as it contains a bug fix that is needed to copy content from one language to another in the CMS: infoportugal/wagtail-modeltranslation#201

Based off changes in #115 to show test status after change.

### CODE REVIEW

**Comment by dalepotter** [comment]
Updating the base branch so that the correct commits show (now that #115 has been merged)

**Comment by dalepotter** [comment]
Blocked pending error on Travis build: https://travis-ci.org/IATI/preview-website/builds/380196717

I've not found a way to proceed. As such, I've raised an issue in the wagtail-modeltranslation repo: https://github.com/infoportugal/wagtail-modeltranslation/issues/206

**Comment by allthatilk** [comment]
Have updated the Wagtail-Modeltranslation issue to reflect root of problem. Will have to wait until this third party module is updated with the Django 2.0 compatible fix: https://github.com/infoportugal/wagtail-modeltranslation/issues/206#issuecomment-395035084

**Comment by dalepotter** [comment]
Changing base branch to `dev` as we have eliminated the temporary temporary dev branch when #4 was merged.

**Comment by samuele-mattiuzzo** [comment]
How relevant is this work still?

**Comment by akmiller01** [comment]
Found this fix in Dale's original issue: https://github.com/infoportugal/wagtail-modeltranslation/issues/206#issuecomment-460613318

Tested the solution above with a round of `save_trans` and `load_trans` and version 0.10b1 works just fine (however more modern versions have higher Django dependencies than we presently have, so maybe if we update Wagtail/Django we can update this even futher). Also while testing I found some issues with the management commands. Rather than rebasing this I've made a new PR: https://github.com/IATI/IATI-Standard-Website/pull/394

**Pull request closed without merging**
