### PR TITLE
Feature/search view to page

### PR DESCRIPTION
**Pull request by urlsangel**
When deploying, follow these steps:

`ssh` to server

#### Staging deployment:
- run: `export ELASTICSEARCH_IMAGE_VERSION="6.4.0"`
- run: `dokku elasticsearch:unlink staging staging`
- run: `dokku elasticsearch:destroy staging`
- run: `dokku elasticsearch:create staging`
- run: `dokku elasticsearch:link staging staging`
- local push: `git push staging master:master`

#### WWW deployment:
- run: `export ELASTICSEARCH_IMAGE_VERSION="6.4.0"`
- run: `dokku elasticsearch:unlink www www`
- run: `dokku elasticsearch:destroy www`
- run: `dokku elasticsearch:create www`
- run: `dokku elasticsearch:link www`
- local push: `git push www master:master`

### CODE REVIEW

**Comment by urlsangel** [comment]
Hey @akmiller01

I’ve amended code that I thought might be causing issues in the context processor/templates with an empty db (i.e. travis), and dropped the `create_batch` number down where used in tests from 10 to 4. 

Tests are now passing, but it’s still taking around 40 mins. Crazy.

I’ve merged this branch into the `collation_april_2020` branch and pushed to `dev` for review. 

Is it possible you could check the `.po` file(s) in this branch and check if they are correct/ready for translation? 

It looks to me like they have _lost_ some translation, so it would be good if you could check - see here for example: https://github.com/IATI/IATI-Standard-Website/pull/470/files?file-filters%5B%5D=.po#diff-379094f6bbfdaabfec3a2e05843a3a93L85

**Comment by akmiller01** [comment]
Ah yeah @urlsangel. Is the django.po file in your feature branch based off of master? Because if not, could you try overwriting it with the one from master https://github.com/IATI/IATI-Standard-Website/blob/master/locale/en/LC_MESSAGES/django.po and then makemessages? It should pull in the old one to write the new lines on top.

**Comment by urlsangel** [comment]
@akmiller01 

No, it was from `develop` - I thought it looked funky :-)

I'll re-compile as you've detailed and push changes 👍

**Comment by urlsangel** [comment]
@akmiller01 

I've updated and pushed - I updated the `fr` and `en` `.po` files, is that right?

https://github.com/IATI/IATI-Standard-Website/pull/470/files?file-filters%5B%5D=.po#diff-379094f6bbfdaabfec3a2e05843a3a93L10

**Comment by akmiller01** [comment]
> @akmiller01
> 
> I've updated and pushed - I updated the `fr` and `en` `.po` files, is that right?
> 
> https://github.com/IATI/IATI-Standard-Website/pull/470/files?file-filters%5B%5D=.po#diff-379094f6bbfdaabfec3a2e05843a3a93L10

Yep all looks good!

**Comment by urlsangel** [comment]
French translations all in place now: https://dev.iatistandard.org/fr/search/

**Pull request merged**
