### PR TITLE
Re-add pylint as an automated testing step

### PR DESCRIPTION
**Pull request by andylolz**
pylint was removed in 44fe88a992b54d212d4c243cbf84f79f5947cf26 (possibly by accident, since it’s a really big commit).

This adds it back.

This PR includes two more improvements:
 * cache pip (to speed up the build process)
 * change branch name in travis (it looks like `dev` was renamed `develop`)

### CODE REVIEW

**Comment by samuele-mattiuzzo** [comment]
@Ocre42 to give it a second spin before merging

**Comment by Ocre42** [comment]
I've set attrs to be 19.1 in the requirements as there appears to be a bug when using installations past 19.2 for it. Have another go at testing and I'll be ready to approve.

**Comment by samuele-mattiuzzo** [comment]
Checking, thanks @Ocre42

**Comment by andylolz** [comment]
`attrs` is not a dependency of `pylint` or `pylint-django`, so I don’t think it’s related to this PR.

**Comment by andylolz** [comment]
In any case, though, thanks for reviewing and merging!

**Pull request merged**
