### PR TITLE
Elasticsearch v6 -> 8, into Docker

### PR DESCRIPTION
**Pull request by odscjames**

### CODE REVIEW

**Comment by odscjames** [comment]
Ready for review

I can't now remember why I added curl to the Docker build. I can take it out if wanted.

We turn security off for Elasticsearch. If enabled, SSL also has to be enabled with a self signed cert then getting clients to securely connect gets difficult.

Security via 2 different firewalls; port 9200 isn't available even on VM (only on the docker internal network). And then Azure firewalls port 9200 anyway.

**Comment by odscjames** [comment]
Prod deploy obvs not tested, double check that's the same as dev deploy pls

**Comment by odscjames** [comment]
I tested restarting VM too

**Comment by Bjwebb** [comment]
I like this approach. I still need to review the detail.

**Pull request merged**
