### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by allthatilk**
Update README:
- Site is now live so no longer Alpha
-  `_translation` is no longer necessary on migration related management commands
- Make nicer to read

### CODE REVIEW

**Comment by allthatilk** [comment]
Looks like Travis cancelled out on the build. Can confirm no code changes in this one.

**Comment by samuele-mattiuzzo** [comment]
> Looks like Travis cancelled out on the build. Can confirm no code changes in this one.

I manually cancelled it after the 4th failure in a row trying to figure out why it was failing: although I know it's only touching the readme file, I needed to make sure we didn't create any about pages from said readme / don't have any tests reading or expecting anything existing within it.

Since we're here, can you change the base to `dev` please as we're doing `feature` -> `dev` -> `master`? Thank you!

**Comment by samuele-mattiuzzo** [comment]
Sigh, silly Travis is silly, probably overloaded and can't bear to wait for our selenium builds to complete. Victim of its own success, we'll have to wait till this build passes or disable selenium tests alltogether.

**Comment by allthatilk** [comment]
Yeah those selenium tests.... sorry about that :woman_shrugging:  but we didn't have time to really plan testing or experiment with testing or fix testing... *sigh* is sudo still enabled? That fixed Travis pooping itself before finishing the build in the past

**Comment by samuele-mattiuzzo** [comment]
Yeah I think it is, apparently this issue might be due to Travis' amount of resources not being enough for our pool of tests to complete without it complaining (each failure, the timeout window shortened, the first time around it waited 17 minutes; for the last run it was just 10). We'll wait till Monday, otherwise I'll push a more relaxed waiting time.

**Comment by allthatilk** [comment]
Hmmm, looks like all PRs are failing except the now very out of date test refactor incomplete one. Also the `_translation` should be removed from the travis file now too. Want me to make another PR for that? (I'm gunning for that Hacktoberfest tee xD)

**Comment by samuele-mattiuzzo** [comment]
Ah right. You could update this one maybe?

**Comment by allthatilk** [comment]
Yeah I'll give it a go this weekend :+1:

**Pull request merged**
